
[db]
username = "yicchen"
password = "datalab"
db_name = "yicchen"
table_name = "y2017_16"
port = "5433"
host = "localhost"

[generator.fields]
agg_fields = [0]
select_fields = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
group_fields = [] # respect to select_fields

[generator.normal]
means = [[1, 2, 40, 25, 65, 65, 1, 125, 16, 120, 225, 250, 1, 3, 8, 6],
         [0, 0, 10,  5, 10, 10, 1,  10,  3,  10,  20,  20, 0, 0, 1, 1]]
std_devs = [[1, 1, 10,  6, 16, 16, 1, 30,  4,  30,  56,  62, 1, 1, 2, 2],
            [1, 1, 10,  6, 16, 16, 1, 30,  4,  30,  56,  62, 1, 1, 2, 2]]
